export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_FAIL';

export const GET_OG_START = 'GET_OG_START';
export const GET_OG_SUCCESS = 'GET_OG_SUCCESS';
export const GET_OG_FAIL = 'GET_OG_FAIL';
